redis_client_port: 6379
redis_cluster_port: 16379

redis_verrsion: "8.6.1"

ansible_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/redis-cluster.pem

redis_admin_password: "RedisAdmin@2026"
redis_app_password: "RedisApp@2026"
redis_repl_password: "RedisRepl@2026"

backup_file: "backup_redis-01"
backup_timestamp: "1781058291"