- name: Stop Redis service
  systemd:
    name: redis-server
    state: stopped
  delegate_to: "{{ groups['redis'][0] }}"
  tags: test_failover

- name: Check cluster nodes after stop redis-01
  command: redis-cli --user admin -a '{{ redis_admin_password }}' -c -h {{ hostvars[groups["redis"][1]]["ansible_host"] }} -p {{ redis_client_port }} cluster nodes
  delegate_to: "{{ groups['redis'][1] }}"
  run_once: true
  register: redis_cluster_nodes_after_stop
  changed_when: false
  tags: test_failover

- name: Display result
  debug:
    msg: "{{ redis_cluster_nodes_after_stop.stdout }}"
  tags: test_failover

- name: Start Redis service
  systemd:
    name: redis-server
    state: started
  delegate_to: "{{ groups['redis'][0] }}"
  tags: test_failover

- name: Check cluster nodes after redis-01 rejoin
  command: redis-cli --user admin -a '{{ redis_admin_password }}' -c -h {{ hostvars[groups["redis"][1]]["ansible_host"] }} -p {{ redis_client_port }} cluster nodes
  delegate_to: "{{ groups['redis'][1] }}"
  run_once: true
  register: redis_cluster_nodes_after_rejoin
  changed_when: false
  tags: test_failover

- name: Display result
  debug:
    msg: "{{ redis_cluster_nodes_after_rejoin.stdout }}"
  tags: test_failover

- name: Test write after failover
  command: redis-cli --user admin -a '{{ redis_admin_password }}' -c -h {{ hostvars[groups["redis"][1]]["ansible_host"] }} -p {{ redis_client_port }} set ha:test2 failover
  delegate_to: "{{ groups['redis'][1] }}"
  run_once: true
  register: redis_write_after
  changed_when: false
  tags: test_failover

- name: Display write result
  debug:
    msg: "{{ redis_write_after.stdout }}"
  tags: test_failover

- name: Test read after failover
  command: redis-cli --user admin -a '{{ redis_admin_password }}' -c -h {{ hostvars[groups["redis"][1]]["ansible_host"] }} -p {{ redis_client_port }} get ha:test2
  delegate_to: "{{ groups['redis'][1] }}"
  run_once: true
  register: redis_read_after
  changed_when: false
  tags: test_failover

- name: Display read result
  debug:
    msg: "{{ redis_read_after.stdout }}"
  tags: test_failover

- name: Check cluster nodes after recovery
  command: redis-cli --user admin -a '{{ redis_admin_password }}' -c -h {{ hostvars[groups["redis"][1]]["ansible_host"] }} -p {{ redis_client_port }} cluster nodes
  delegate_to: "{{ groups['redis'][1] }}"
  run_once: true
  register: redis_cluster_nodes_recovery
  changed_when: false
  tags: test_failover

- name: Display recovery result
  debug:
    msg: "{{ redis_cluster_nodes_recovery.stdout }}"
  tags: test_failover

- name: Check replication after recovery
  command: redis-cli --user admin -a '{{ redis_admin_password }}' -h {{ hostvars[groups["redis"][0]]["ansible_host"] }} -p {{ redis_client_port }} info replication
  delegate_to: "{{ groups['redis'][0] }}"
  run_once: true
  register: redis_replication_recovery
  changed_when: false
  tags: test_failover

- name: Display replication recovery result
  debug:
    msg: "{{ redis_replication_recovery.stdout }}"
  tags: test_failover

