---
- name: Add hosts entries
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
    state: present
  loop: "{{ groups['redis'] }}"

- name: Download Redis GPG key
  get_url:
    url: https://packages.redis.io/gpg
    dest: /tmp/redis.gpg

- name: Convert GPG key
  command:
    cmd: gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg /tmp/redis.gpg
    creates: /usr/share/keyrings/redis-archive-keyring.gpg

- name: Add Redis repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb {{ ansible_distribution_release }} main"
    filename: redis
    state: present

- name: Install Redis
  apt:
    name: redis
    state: present
    update_cache: true

- name: Check Redis version
  command: redis-server --version
  register: redis_version
  changed_when: false

- name: Display Redis version
  debug:
    msg: "{{ redis_version.stdout }}"

- name: Status Redis service
  command: systemctl status redis-server
  register: redis_status
  changed_when: false
  failed_when: false

- name: Display Redis status
  debug:
    msg: "{{ redis_status.stdout }}"

- name: Check memory
  command: redis-cli --user admin -a '{{ redis_admin_password }}' -c -h {{ hostvars[groups["redis"][0]]["ansible_host"] }} -p {{ redis_client_port }} info memory
  run_once: true
  delegate_to: "{{ groups['redis'][0] }}"
  register: redis_memory
  changed_when: false

- name: Display memory result
  debug:
    msg: "{{ redis_memory.stdout }}"

- name: Check slot coverage
  command: redis-cli --user admin -a '{{ redis_admin_password }}' cluster info
  delegate_to: "{{ groups['redis'][0] }}"
  register: redis_slot
  changed_when: false

- name: Display slot coverage result
  debug:
    msg: "{{ redis_slot.stdout }}"

- name: Check replication
  command: redis-cli --user admin -a '{{ redis_admin_password }}' info replication
  register: redis_replication
  changed_when: false

- name: Display replication result
  debug:
    msg: "{{ redis_replication.stdout }}"
