- name: Add node redis-07
  command: >
    redis-cli --cluster add-node
    {{ hostvars[groups["redis_new"][0]]["ansible_host"] }}:{{ redis_client_port }}
    {{ hostvars[groups["redis"][0]]["ansible_host"] }}:{{ redis_client_port }}
    --user admin
    -a '{{ redis_admin_password }}'
  delegate_to: "{{ groups['redis'][0] }}"
  run_once: true
  register: redis_add_node
  changed_when: false

- name: Display result
  debug:
    msg: "{{ redis_add_node.stdout }}"

- name: Wait for cluster to sync
  pause:
    seconds: 10

- name: Rebalance slots
  command: >
    redis-cli --cluster rebalance
    {{ hostvars[groups["redis"][0]]["ansible_host"] }}:{{ redis_client_port }}
    --user admin
    -a '{{ redis_admin_password }}'
    --cluster-use-empty-masters
  delegate_to: "{{ groups['redis'][0] }}"
  run_once: true
  register: redis_rebalance
  changed_when: false

- name: Display result
  debug:
    msg: "{{ redis_rebalance.stdout }}"

- name: Check cluster after scale
  command: >
    redis-cli --cluster check
    {{ hostvars[groups["redis"][0]]["ansible_host"] }}:{{ redis_client_port }}
    --user admin
    -a '{{ redis_admin_password }}'
  delegate_to: "{{ groups['redis'][0] }}"
  run_once: true
  register: redis_cluster_check
  changed_when: false

- name: Display result
  debug:
    msg: "{{ redis_cluster_check.stdout }}"