---
- name: Provision new node
  hosts: redis_new
  become: true
  vars_files:
    - ../group_vars/redis-cluster.yml
  roles:
    - common
    - installation
    - cluster
    - testing

- name: Scale Redis cluster
  hosts: redis_new
  become: true
  vars_files:
    - ../group_vars/redis-cluster.yml
  roles:
    - scale